### ISSUE TITLE
关于训练时长问题

### ISSUE THREAD

**Issue by MSL502** [jinnh/GSAD#10]
尊敬的作者，您好：
       我想请问一下您两个阶段训练总时长大约是多久呢，第一个阶段和第二阶段分别训练多久呢

**Comment by jinnh** [comment]
@MSL502 哈喽，感谢对我们工作的关注。以使用单张RTX3090为例，第一个阶段和第二阶段分别大概需要28+、60+左右小时。考虑到服务器GPU和CPU多人使用的情况，时间可能会有差异。同时我们也有提供第一阶段的[预训练模型](https://drive.google.com/drive/folders/139LvNvVv0ATp3-mIcSipnl1YauDcaVyf)，如有需要加快训练，可以直接下载使用~

**Comment by finnn00** [comment]
作者你好，

1，关于训练时的train_loss和valid_loss可视化，我看到你写了
            tb_logger_train = SummaryWriter(log_dir=log_dir_train)
            tb_logger_valid = SummaryWriter(log_dir=log_dir_valid)
但是没有写可视化的code？（可能是我疏漏没看到）是否可以麻烦分享一下？或者请教一下，感谢~

2，还有关于pretrained_uncertainty_models
                 u_lolv1_gen.pth
                 u_lolv1_opt.pth
      **gen**和**opt**有什么区别呢？
      期待您的回复~
