### ISSUE TITLE
Shape issue

### ISSUE THREAD

**Issue by beratersari** [jinnh/GSAD#11]
```
x, t=t, noise=self.denoise_fn(torch.cat([condition_x, x], dim=1), noise_level)[0])
  File "/home/onureker/anaconda3/envs/GlobalDiff/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/onureker/berat-projects/image_enhancment/GSAD/model/ddpm_modules/unet.py", line 268, in forward
    x = layer(torch.cat((x, temp__), dim=1), noise_level)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 162 but got size 161 for tensor number 1 in the list.
```
The code normally works well. However, when I try to add a new pair in low and high folders for testing, It gives an error. How can I fix that?

**Comment by jinnh** [comment]
Hi, @beratersari. Thanks for your interest. For new data, it is advisable to resize or pad the new low-light image during the data loading phase, adjusting its length and width to be multiples of 16. Then, re-crop or resize the output image back to its original size.
