### ISSUE TITLE
Black images occur when set "n_timestep"=500 for testing in lolv1_test.json

### ISSUE THREAD

**Issue by MqLeet** [jinnh/GSAD#12]
Hi, thanks for your great work!

I noticed that for the lolv1 dataset, you set the n_timestep=500 for the training stage, but n_timestep=20 for the testing stage, it's interesting.
But when I set the n_timestep=500 for the testing stage, the output image was black, so I was puzzled.

Can you help me?

**Comment by jinnh** [comment]
We empirically set "linear_start" and "linear_end" using different timesteps. Specifically, for larger timesteps, you can set "linear_start" and "linear_end" to values corresponding to a smaller noise level, akin to the noise level used during the training phase. On the other hand, when the number of timesteps is smaller, you can afford to use a larger noise level. In this case, you would set "linear_start" to a higher value and "linear_end" accordingly.

You may also employ a search algorithm to systematically explore and find the most effective noise settings tailored to the specific timestep configuration being used.
