### ISSUE TITLE
Training without Pretrained models

### ISSUE THREAD

**Issue by suraerturkmen** [jinnh/GSAD#14]
Hi, I want to make a train with my custom dataset. However when I did not provide _gen.pth path, the train.py gave me an error "FileNotFoundError: [Errno 2] No such file or directory: '_gen.pth'". How can I solve it?

**Comment by jinnh** [comment]
Hi, @suraerturkmen, thanks for your interest. I think this issue may be caught when loading the pre-trained uncertainty model in [line 62 of model.py](https://github.com/jinnh/GSAD/blob/6e4895880246124f11fa13e97b95e75c4934b119/model/model.py#L62C116-L62C133). It would help if you had the resume_state_path in [line 12 of train.json](https://github.com/jinnh/GSAD/blob/6e4895880246124f11fa13e97b95e75c4934b119/config/lolv1_train.json#L12C10-L12C22).
