### ISSUE TITLE
Denoise_fn

### ISSUE THREAD

**Issue by iamgchattejee** [jinnh/GSAD#15]
https://github.com/jinnh/GSAD/blob/6e4895880246124f11fa13e97b95e75c4934b119/model/ddpm_modules/diffusion_Pt.py#L69
From where is this denoise_fn being passed here?

**Comment by jinnh** [comment]
Hi, @iamgchattejee, thanks for your interest. The denoise_fn is passed from [here](https://github.com/jinnh/GSAD/blob/6e4895880246124f11fa13e97b95e75c4934b119/model/networks.py#L103).
