### ISSUE TITLE
代码重新训练的问题

### ISSUE THREAD

**Issue by HCL0708** [jinnh/GSAD#16]
作者您好。我在使用您给的代码进行重新训练时发现，训练出来的模型在指标上达不到论文中的指标，在lolv1上只能达到26点多的psnr，并且我还注意到代码中使用了随机种子，我猜想会不会是随机种子产生的问题，能否告知一下您训练中使用的随机种子

**Comment by jinnh** [comment]
哈喽，感谢对我们工作的关注。我想问下26点多的结果是训练是log里面的结果么，如果是的话，你可以用相应的模型跑一下测试代码，看下结果，测试的时候可以选取不用的seed、不同的timestep，可以参考下这个[issue 12](https://github.com/jinnh/GSAD/issues/12)。我训练lolv1的seed是1999，同时你可以加大训练的iteration试试。

**Comment by jinnh** [comment]
我这边是因为测试的时候，为了加快测试，与训练时候的验证使用不用的设置。
训练：`"train": {
                "schedule": "linear",
                "n_timestep": 500,
                "linear_start": 1e-4,
                "linear_end": 2e-2
            },
            "val": {
                "schedule": "linear",
                "n_timestep": 500,
                "linear_start": 1e-4,
                "linear_end": 2e-2
            }`
   测试：`"train": {
                "schedule": "linear",
                "n_timestep": 500,
                "linear_start": 1e-4,
                "linear_end": 2e-2
            },
            "val": {
                "schedule": "linear",
                "n_timestep": 20,
                "linear_start": 6e-4,
                "linear_end": 8.8e-1
            }`
   如果你测试的使用也是使用训练时候的验证配置，我想结果应该是和你训练的log差不多的。

**Comment by HCL0708** [comment]
> 我这边是因为测试的时候，为了加快测试，与训练时候的验证使用不用的设置。 训练：`"train": { "schedule": "linear", "n_timestep": 500, "linear_start": 1e-4, "linear_end": 2e-2 }, "val": { "schedule": "linear", "n_timestep": 500, "linear_start": 1e-4, "linear_end": 2e-2 }` 测试：`"train": { "schedule": "linear", "n_timestep": 500, "linear_start": 1e-4, "linear_end": 2e-2 }, "val": { "schedule": "linear", "n_timestep": 20, "linear_start": 6e-4, "linear_end": 8.8e-1 }` 如果你测试的使用也是使用训练时候的验证配置，我想结果应该是和你训练的log差不多的。

好的，非常感谢您的耐心解答

**Comment by HCL0708** [comment]
> 我这边是因为测试的时候，为了加快测试，与训练时候的验证使用不用的设置。 训练：`"train": { "schedule": "linear", "n_timestep": 500, "linear_start": 1e-4, "linear_end": 2e-2 }, "val": { "schedule": "linear", "n_timestep": 500, "linear_start": 1e-4, "linear_end": 2e-2 }` 测试：`"train": { "schedule": "linear", "n_timestep": 500, "linear_start": 1e-4, "linear_end": 2e-2 }, "val": { "schedule": "linear", "n_timestep": 20, "linear_start": 6e-4, "linear_end": 8.8e-1 }` 如果你测试的使用也是使用训练时候的验证配置，我想结果应该是和你训练的log差不多的。

作者您好，我想知道训练时："val": { "schedule": "linear", "n_timestep": 500, "linear_start": 1e-4, "linear_end": 2e-2 }为什么可以改成测试时："val": { "schedule": "linear", "n_timestep": 20, "linear_start": 6e-4, "linear_end": 8.8e-1 }，n_timestep变小了，同时修改了linear_start和linear_end。为什么这样修改是可行的？而且我注意到您代码中去噪过程的公式似乎不像是ddpm和ddim的去噪过程中的公式

**Comment by jinnh** [comment]
在测试的时候使用小的n_timestep=20，相比于n_timestep=500，每一步需要去掉更多的噪声，对应的noise_level就相应的变大，所以相应的改动"linear_start" 和 "liner_end"。这边我们只是经验性的选取了，当然还可以采用搜索算法来系统地探索和查找适合所使用的特定时间步长配置的最有效的噪声设置。

**Comment by HCL0708** [comment]
> 在测试的时候使用小的n_timestep=20，相比于n_timestep=500，每一步需要去掉更多的噪声，对应的noise_level就相应的变大，所以相应的改动"linear_start" 和 "liner_end"。这边我们只是经验性的选取了，当然还可以采用搜索算法来系统地探索和查找适合所使用的特定时间步长配置的最有效的噪声设置。

好的，抱歉再次打扰您一下，我注意到您代码中去噪过程的公式似乎不像是ddpm去噪过程中的公式，我想问一下这样修改为什么可行？

**Comment by jinnh** [comment]
ddpm的话是把t作为condition输入网络，我们代码里面是把t对应的noise_level作为condition输入网络哈。你可以看下这篇[论文](https://ieeexplore.ieee.org/document/9887996)。

**Comment by HCL0708** [comment]
> ddpm的话是把t作为condition输入网络，我们代码里面是把t对应的noise_level作为condition输入网络哈。你可以看下这篇[论文](https://ieeexplore.ieee.org/document/9887996)。

好的，感谢您的回复，我知道您代码中使用了t对应的noise_level作为输入，我指的是您代码中的去噪公式似乎和您论文中公式2的去噪公式不太一样

**Comment by jinnh** [comment]
是指的公式中 $+\sigma_t \mathbf{Z}$ 和代码里面的不一样么，代码中`+ noise * (0.5 * model_log_variance).exp()`的`(0.5 * model_log_variance).exp()`是等于 $\sigma_t$ 的。你可以结合下这个[论文](https://ieeexplore.ieee.org/document/9887996)里面的公式4再看下哈。

**Comment by HCL0708** [comment]
> 是指的公式中 +σtZ 和代码里面的不一样么，代码中`+ noise * (0.5 * model_log_variance).exp()`的`(0.5 * model_log_variance).exp()`是等于 σt 的。你可以结合下这个[论文](https://ieeexplore.ieee.org/document/9887996)里面的公式4再看下哈。

好的，我看懂了，非常感谢

**Comment by HCL0708** [comment]
> 我这边是因为测试的时候，为了加快测试，与训练时候的验证使用不用的设置。 训练：`"train": { "schedule": "linear", "n_timestep": 500, "linear_start": 1e-4, "linear_end": 2e-2 }, "val": { "schedule": "linear", "n_timestep": 500, "linear_start": 1e-4, "linear_end": 2e-2 }` 测试：`"train": { "schedule": "linear", "n_timestep": 500, "linear_start": 1e-4, "linear_end": 2e-2 }, "val": { "schedule": "linear", "n_timestep": 20, "linear_start": 6e-4, "linear_end": 8.8e-1 }` 如果你测试的使用也是使用训练时候的验证配置，我想结果应该是和你训练的log差不多的。

作者您好，您在测试时使用的是类似于ddpm的去噪公式，为什么不是用类似于ddim的去噪公式实现跳步，而是自己对n_timestep，"linear_start" 和 "liner_end"进行修改
