### ISSUE TITLE
about training time

### ISSUE THREAD

**Issue by conutqiqi** [jinnh/GSAD#19]
Thank you very much for the efforts . Recently, I tried to reproduce the training process, but found that the training time was quite long. May I ask the author how long the model ran and what kind of graphics card was used？

**Comment by jinnh** [comment]
Hello, thank you for your interest. We utilized the RTX3090 for training. Taking a single RTX3090 as an example, the first stage and the second stage take about 28+ and 60+ hours respectively. Taking into account the multi-person use of the server GPU and CPU, the time may vary. At the same time, we also provide the first-stage [pre-training model](https://drive.google.com/drive/folders/139LvNvVv0ATp3-mIcSipnl1YauDcaVyf). If you need to speed up the training, you can download it directly and use it.

**Comment by biedaxiaohua** [comment]
Thanks for your work. Can you please tell me if the first stage of training is also done on the whole diffusion model? I noticed during training that I am only using about 4G of memory with my batch-size setting of 8. Is there a problem with this? Thank you for your answer!

**Comment by jinnh** [comment]
@biedaxiaohua Thank you for your interest in our work. I am sorry for the late response. This is normal since we only use the patch size of 96x96.
