### ISSUE TITLE
为什么文中报的指标偏高？

### ISSUE THREAD

**Issue by caiyuanhao1998** [jinnh/GSAD#2]
<img width="1254" alt="截屏2023-10-31 下午2 20 25" src="https://github.com/jinnh/GSAD/assets/48472661/fb2030be-5ded-4981-8792-56120228d8ee">
<img width="841" alt="截屏2023-10-31 下午2 19 55" src="https://github.com/jinnh/GSAD/assets/48472661/9f827179-6429-468f-9f84-e5254f79e9cb">

你好，文中报的其他论文的指标为什么比之前的论文自己报的要高这么多？

**Comment by ZHU-Zhiyu** [comment]
@caiyuanhao1998 你好，我们论文中的所有指标统一采用的LLFlow计算metric的方法。

**Comment by caiyuanhao1998** [comment]
为什么这个metric会高这么多？

**Comment by caiyuanhao1998** [comment]
我看了一眼，LLFlow把GT拿出来finetune，你是这么做的吗？

https://github.com/wyf0912/LLFlow/issues/8
https://github.com/wyf0912/LLFlow/issues/31

**Comment by ZHU-Zhiyu** [comment]
他用GT不是finetune，其实是来标定图像均值。对的，我们跟他同样的操作。包括所有的对比方法都是一样的操作

**Comment by caiyuanhao1998** [comment]
LLFlow 就是用 mean GT 来 finetune brightness 呀，这么搞本身就违规了。这些方法在原论文中正经训练时，都是不能包含任何GT信息的。

**Comment by ZHU-Zhiyu** [comment]
在训练的时候，任何model 都没有见过任何GT的图片，只是这个metric测试的时候去掉mean value 的影响。模型里没有任何 testing set GT的信息。

**Comment by caiyuanhao1998** [comment]
你点开我留的 issue 看看

**Comment by caiyuanhao1998** [comment]
怎么去掉 mean value 的影响？

**Comment by ZHU-Zhiyu** [comment]
这是计算metric的code
```gt_img = gt_img / 255. 
normal_img = normal_img / 255.
mean_gray_out = cv2.cvtColor(normal_img.astype(np.float32), cv2.COLOR_BGR2GRAY).mean()
mean_gray_gt = cv2.cvtColor(gt_img.astype(np.float32), cv2.COLOR_BGR2GRAY).mean()
#这个地方相当于用GT 做了rescale 来去除均值的影响
normal_img_adjust = np.clip(normal_img * (mean_gray_gt / mean_gray_out), 0, 1)```

再次声明，我们的模型在任何时候绝对没有看过任何 testing set GT的信息。

**Comment by caiyuanhao1998** [comment]
你训练时没有用，但是你测试的时候用了呀，你这是在用GT来矫正你的模型输出。
这个均值是光照度信息，这个比值就是全局光照强度的比值，这么做也是违规了。本身GT就是不可见的，唯一的作用就是测评输出，你现在把GT拿来矫正输出，这么做是不对的。

**Comment by ZHU-Zhiyu** [comment]
测试的时候，是这个metric用了gt来加了一步矫正，对于low-light enhancement 来说提升亮度的同时，能不能同时去噪，还原正确的纹理，这些只有整体亮度调节之后计算psnr才能显示出来。你可以再看看，对比下图像的细节。

**Comment by caiyuanhao1998** [comment]
什么叫做进一步矫正，GT本来就是不能用的，你用GT才把指标刷这么高，这本身就是在作弊，不要避重就轻。

**Comment by caiyuanhao1998** [comment]
https://paperswithcode.com/sota/low-light-image-enhancement-on-lol-v2-1
https://paperswithcode.com/sota/low-light-image-enhancement-on-lol-v2

paper with code 上边的这两个track是我 set up 的，里面没有方法用这种metric。别把你的方法加进来。
至于 https://paperswithcode.com/sota/low-light-image-enhancement-on-lol 这个track，绝大部分都没有用GT来提升最终的指标，我建议你最好还是另起一个metric。

**Comment by ZHU-Zhiyu** [comment]
对于LOL-V2 我们会做自己的track，但是LOL现在榜单最近一年的SOTA大部分都是这么算的。

**Comment by caiyuanhao1998** [comment]
啥呀，我就不这么算，这样子搞本身就是错的，测试的时候本身就只能有low-light。

至少三个审稿人难道没人问这个指标的问题吗？

**Comment by ZHU-Zhiyu** [comment]
你爱再算咋算

**Comment by caiyuanhao1998** [comment]
我能理解的这么做的唯一意义就是把指标刷高

**Comment by caiyuanhao1998** [comment]
除了你和 LLFlow，你还能举出什么例子么？就开源的代码，拿GT来提升指标的

**Comment by dsjiaod** [comment]
> 算了，不说了，给你个面子，把这个issue删掉。

Learning Semantic-Aware Knowledge Guidance for Low-Light Image Enhancement. CVPR2023.
![image](https://github.com/jinnh/GSAD/assets/152845676/56b4da39-ad24-4199-924f-06ddbf859f1e)
Hi，这篇CVPR的文章也是，在low-light enhancement这个小领域里边，好像一般如果比较方法包含LLFlow的话，一般都会用到这个gt来矫正的操作，虽然这个操作是不正确的。
我之前没有用这个操作，但是审稿人又问我没有和LLFlow比较，点数为什么比LLFlow低这么多，又没法在rebuttal的时候和审稿人清楚的解释。
不过如果是专门做low-light enhancement的话应该很早就主要到LLFlow用的这个操作了吧，默认和他比较都会用到这个的。

**Comment by JianghaiSCU** [comment]
> > 算了，不说了，给你个面子，把这个issue删掉。
> 
> Learning Semantic-Aware Knowledge Guidance for Low-Light Image Enhancement. CVPR2023. ![image](https://private-user-images.githubusercontent.com/152845676/288097165-56b4da39-ad24-4199-924f-06ddbf859f1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4MzIzMDcsIm5iZiI6MTcwMTgzMjAwNywicGF0aCI6Ii8xNTI4NDU2NzYvMjg4MDk3MTY1LTU2YjRkYTM5LWFkMjQtNDE5OS05MjRmLTA2ZGRiZjg1OWYxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQwMzA2NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzJmZDFiYjY5MWI4ZTMyYTViNzcxNjM0NjBiZDdmNWVkY2IyZWY4MGJkYWM0NjFhNTg4MGUwYWE2ZGYwZDA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lL-RaqB5T_EE00K7uBk-CmwYk4chySZKeHAOky12W_4) Hi，这篇CVPR的文章也是，在low-light enhancement这个小领域里边，好像一般如果比较方法包含LLFlow的话，一般都会用到这个gt来矫正的操作，虽然这个操作是不正确的。 我之前没有用这个操作，但是审稿人又问我没有和LLFlow比较，点数为什么比LLFlow低这么多，又没法在rebuttal的时候和审稿人清楚的解释。 不过如果是专门做low-light enhancement的话应该很早就注意到LLFlow用的这个操作了吧，默认和他比较都会用到这个的。 上面提到到的这篇CVPR的文章也是开源的，代码里可以看到。

为啥不能直接说他不公平呢，可以参考LLDiffusion: Learning Degradation Representations in Diffusion Models for Low-Light Image Enhancement (https://arxiv.org/pdf/2307.14659.pdf)里的说法，不跟LLFlow这些用gt mean来做finetune的比.
![3cccb0feeb7762058a7ca49591c4ec03](https://github.com/jinnh/GSAD/assets/86350392/d586e708-3e1c-48da-9f46-355fa4fabe95)

**Comment by tongchangD** [comment]
@caiyuanhao1998  别给这个所谓的面子，很多东西都是需要讨论的，不管谁对谁否错，或许都没有错，讨论多了进步也就多了

**Comment by finnn00** [comment]
作者你好，如果我要重新训练GASD，不用GT mean的话应该怎么做呢？用min-max nomalization可以吗？

**Comment by jinnh** [comment]
@finnn00 你好，感谢对我们工作的关注。我们在训练中并没有使用到GT mean, 如果想要得到GSAD不使用GT mean的结果，只需要在测试阶段将使用GT mean的代码注释掉即可，即test.py的[L165-L172](https://github.com/jinnh/GSAD/blob/6e4895880246124f11fa13e97b95e75c4934b119/test.py#L165).

**Comment by lxr1137805288** [comment]
很多文章都是用的GT mean，提出此issue的兄弟看的论文还是太少了
