### ISSUE TITLE
About json files for Synthetic and Real in the LOLv2 dataset

### ISSUE THREAD

**Issue by dadaplm** [jinnh/GSAD#20]
Hello, the config file misses the training json files for the LOLv2_Synthetic and LOLv2_Real datasets. Can you provide these two corresponding json files? Thank you.

**Comment by jinnh** [comment]
Hi, @dadaplm. Regarding the training of LOLv2-real and LOLv2-synthetic, we have not made specific parameter adjustments. The parameters used can directly refer to the training json file of LOLv1.
