### ISSUE TITLE
Meaning of train.py Whether or not two separate complete models were trained

### ISSUE THREAD

**Issue by pepper725** [jinnh/GSAD#21]
Hi, what part of the model do the two lines of code below correspond to? The first line of code is for training the uncertainty model and the second line of code is for training a model that is both uncertainty and globally aware, meaning that both models have outputs? In other words, both trained models have outputs, the diffusion model trained in the first line takes into account only the uncertainty, while the model trained in the second line takes into account both the uncertainty and the globally aware structure, right? Both rows correspond to two complete models. Am I correct in saying that?

## train uncertainty model
python train.py -uncertainty   --config ./config/llie_train_u.json        --dataset ./config/customized_dataset.yml 
## train global structure-aware diffusion
python train.py                 --config ./config/customized_dataset_train.json         --dataset ./config/customized_dataset.yml

**Comment by jinnh** [comment]
Hi, @pepper725. You are mostly accurate but could be clearer and more precise. The first line aims to train an uncertainty model, which is utilized to generate an uncertainty map during the second line's training, making it take uncertainty into account. Besides, the trained uncertainty model is frozen during the second line's training.
