### ISSUE TITLE
在自定义数据集上测试的请教

### ISSUE THREAD

**Issue by pepper725** [jinnh/GSAD#22]
你好 请问在自己数据集上训练时，在训练uncertainty是不需要设置resume_state 在训练global_awareness时需要设置resume_state为./uncertainty/latest 那么请问在测试的时候 我应该如何设置test.json里的resume_state

**Comment by jinnh** [comment]
@pepper725 你好，在测试的时候，只需要将训练好的模型对应的路径放置resume_state上就可以，例如`"resume_state": "./checkpoints/xxxxxxx_gen.pth"`。

**Comment by pepper725** [comment]
test里的resume_state的路径 跟 train里的resume_state的路径一样吗

**Comment by pepper725** [comment]
@jinnh

**Comment by pepper725** [comment]
![image](https://github.com/jinnh/GSAD/assets/114202918/89d67865-1427-4c64-a57d-a4ac7cdfed71)

**Comment by jinnh** [comment]
test和train里面的resume_state的路径不一样的。train json里面resume_state是加载的不确定模型的路径。你要测试的话，把你训练好的模型路径放到test里面的resume_state，或者可以下载我提供的训练好的模型。例如测试LOLv1;`"resume_state": "./checkpoints/lolv1_gen.pth"`
