### ISSUE TITLE
Build my own dataset

### ISSUE THREAD

**Issue by 12qew** [jinnh/GSAD#24]
Thank you very much for your outstanding work. How to create a yaml file and a json file for a custom dataset? I look forward to your reply.

**Comment by jinnh** [comment]
@12qew Thank you for your interest in our work. I am sorry for the late response. Please refer to the section on [Training on the customized dataset](https://github.com/jinnh/GSAD#training-on-the-customized-dataset). If you have any questions, feel free to ask.
