### ISSUE TITLE
关于指数移动平均

### ISSUE THREAD

**Issue by shikailun-up** [jinnh/GSAD#25]
感谢您的工作，我注意到您在论文中提到了在训练过程中使用了指数移动平均，但是我在代码中并没有找到相应的代码，请问您是如何进行指数移动平均的，可以提供相应代码吗？另外的问题是关于学习率，您在训练过程中学习率是固定不变的吗？

**Comment by jinnh** [comment]
@shikailun-up 哈喽，感谢对我们工作的关注。实际上，在此版本中我们并未在训练过程中使用指数移动平均技术。论文中可能有误导描述，对此我们表示歉意。如果您对EMA感兴趣，可以参考TensorFlow或PyTorch中的相关模块。关于学习率，我们在整个训练过程中保持其不变，并未进行动态调整。
