### ISSUE TITLE
Custom Datasets

### ISSUE THREAD

**Issue by rameshshreyas** [jinnh/GSAD#3]
Hi,
Thank you so much fo building this! I am learning to implement this and wanted to run this model on my existing dataset. Could you provide some pointers as to how do I go about it?

**Comment by ZHU-Zhiyu** [comment]
Hi @rameshshreyas, Thanks very much for your interest and attention. We will give detailed instructions for training on a customized dataset later today.

**Comment by ZHU-Zhiyu** [comment]
Hi @rameshshreyas ，Please refer to the section on [Training on the customized dataset](https://github.com/jinnh/GSAD#training-on-the-customized-dataset). If any question, feel free to ask.
