### ISSUE TITLE
测试数据指标比文中指标低

### ISSUE THREAD

**Issue by ShuimuChen-hyq** [jinnh/GSAD#30]
![image](https://github.com/user-attachments/assets/3f3c0110-e5c9-4dab-9bfb-8ea295eb09ee)
![image](https://github.com/user-attachments/assets/ee12a986-28d7-443d-95c6-cc7fdfd65afb)
您好，为什么运行您的test代码，LOLv1数据指标偏低呢

**Comment by jinnh** [comment]
哈喽，感谢对我们工作的关注。这可能是由于不同的设备或seed导致的。
