### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by igormahall** [jinnh/GSAD#4]
Hello.

Thanks for sharing the unpaired test test.

I tried to run it by:

$ python test_unpaired.py --config config/test_unpaired.json

But got the mentioned error:
[errorlog.txt](https://github.com/jinnh/GSAD/files/13393196/errorlog.txt)

Could you please support me?
Thanks in advance.

**Comment by jinnh** [comment]
Hi, @igormahall, thank you for your interest in our work. You may consider utilizing a GPU with a larger memory capacity or testing the image at a slightly reduced resolution.
