### ISSUE TITLE
NIQE codes

### ISSUE THREAD

**Issue by Xingshi-tech** [jinnh/GSAD#6]
I found some methods online for calculating the NIQE metric, and I used them to test the enhancement results, but the results I got were inconsistent with the ones provided in your paper. If possible, could you please share the code you used to calculate the NIQE?

**Comment by ZHU-Zhiyu** [comment]
Hi @Xingshi-tech , Thanks for your interest. We will release the corresponding code soon (before this weekend).

**Comment by Xingshi-tech** [comment]
Thanks for reply

**Comment by jinnh** [comment]
Hi, @Xingshi-tech. For NIQE codes, please refer to  [metrics in Lighting-the-Darkness-in-the-Deep-Learning-Era-Open](https://github.com/Li-Chongyi/Lighting-the-Darkness-in-the-Deep-Learning-Era-Open#metrics).

When testing the unpaired data (e.g., LIME, NPE, MEF, DICM, and VV), you can try to use different pre-trained models (It is recommended to use `'lolv2_syn_gen.pth'`) and employ `various sampling steps and noise levels` to obtain visual-pleasing results by modifying these terms in the 'test_unpaired.json'. 

For example, when testing LIME, we use 'lolv2_syn_gen.pth' with the sampling setting `
"val": {
                "schedule": "linear",
                "n_timestep": 10,
                "linear_start": 1e-4,
                "linear_end": 7e-1
            }`.

**Comment by Xingshi-tech** [comment]
Hi,@jinnh. Thanks for your help.
