### ISSUE TITLE
I need your help brother 

### ISSUE THREAD

**Issue by amit-15** [jinnh/GSAD#7]
![Screenshot_2023-12-03-02-05-01-58_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/jinnh/GSAD/assets/74417579/7a4fcaed-9748-4a68-ac58-2420db454764)

I have a doubt about train uncertainty model, can you explain me what is difference between uncertainty model and global structure model while training custom model. And if I train a custom model which line of code I run both line or uncertainty line or global structure line code

**Comment by ZHU-Zhiyu** [comment]
Hi, @amit-15 , thanks for your interest. The uncertainty model is utilized to estimate a weighted mask for trining our diffusion model. And it is only utilized in the training process. For final image reconstruction, we only need the diffusion model. If any question, feel free to ask.

**Comment by amit-15** [comment]
Hi, when i run test_unpaired.py with my dataset its give me this error massage. I highlight the folder structure of unpaired images
![Screenshot 2023-12-09 151614](https://github.com/jinnh/GSAD/assets/74417579/d693d3fd-f443-407a-81ce-b4c6a24e74f6)

**Comment by amit-15** [comment]
This code i run with update test_unpaired.py
![Screenshot 2023-12-09 151407](https://github.com/jinnh/GSAD/assets/74417579/7a2fd511-31d9-410e-8772-f2fa60a26ec2)


![Screenshot 2023-12-09 151810](https://github.com/jinnh/GSAD/assets/74417579/2b48c7ff-c18b-4e9b-abcd-6644917a0a0e)

**Comment by jinnh** [comment]
Hi, @amit-15. You may try the following codes with a more '/' at the end.
`python test_unpaired.py  --config config/test_unpaired.json --input /content/drive/MyDrive/ImageEnhanceExp/GSAD/unpaired_image_folder/`

**Comment by amit-15** [comment]
Thanks you, brother now its working for me
