### ISSUE TITLE
uncertainty estimation model

### ISSUE THREAD

**Issue by zhenyuan1234** [jinnh/GSAD#8]
Can you provide pre-trained weights for the uncertainty estimation model, thanks!

**Comment by zhenyuan1234** [comment]
Thanks for your reply. I have a new problem, how do I solve it.
FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/uncertainty/latest_opt.pth'

**Comment by jinnh** [comment]
Does this happen when you save the weights of the uncertainty model? If yes, please refer to [issue 5](https://github.com/jinnh/GSAD/issues/5). And I have updated the model.py, you can directly update it from [model.py](https://github.com/jinnh/GSAD/blob/main/model/model.py).

**Comment by jinnh** [comment]
@zhenyuan1234 Hi, there is a small bug in model.py. If you are utilizing the pre-trained uncertainty models to initialize the models at the second stage, please update the 'model.py'.

**Comment by pepper725** [comment]
Hi, what part of the model do the two lines of code below correspond to? The first line of code is for training the uncertainty model and the second line of code is for training a model that is both uncertainty and globally aware, meaning that both models have outputs? In other words, both trained models have outputs, the diffusion model trained in the first line takes into account only the uncertainty, while the model trained in the second line takes into account both the uncertainty and the globally aware structure, right? Both rows correspond to two complete models. Am I correct in saying that?

## train uncertainty model
python train.py -uncertainty   --config ./config/llie_train_u.json        --dataset ./config/customized_dataset.yml 
## train global structure-aware diffusion
python train.py                 --config ./config/customized_dataset_train.json         --dataset ./config/customized_dataset.yml
