### ISSUE TITLE
代码问题想要请教

### ISSUE THREAD

**Issue by MrWan001** [jinnh/GSAD#9]
作者你好，我在阅读您的代码，在第二个训练阶段，python train.py --config config/lolv1_train.json --dataset ./config/lolv1.yml，预训练好的uncertainty模型权重是在哪里加载的，我理解到self.netGU是uncertainty模型，我能找到最相关的是被注释掉的这一行，请问uncertainty模型加载预训练权重是在哪一行实现的。期待您的指点。
![image](https://github.com/jinnh/GSAD/assets/126931904/96c872f7-0975-493e-b5e9-630dcd490b18)

**Comment by jinnh** [comment]
@MrWan001 你好，感谢对我们工作的关注。关于这个地方你的理解是没错的，我们也更新了model.py文件, 你可以直接把它取消注释。

**Comment by MrWan001** [comment]
![image](https://github.com/jinnh/GSAD/assets/126931904/e0fb40f2-2f6b-4ebb-a3a3-ee44676ef837)
你好，这里也是个小错误是吧😀
